# Generated by Django 2.1.4 on 2019-02-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('coursename', models.CharField(max_length=5)),
                ('credits', models.FloatField()),
                ('cat1ptr', models.IntegerField(default=0)),
                ('cat2ptr', models.IntegerField(default=0)),
                ('cat3ptr', models.IntegerField(default=0)),
                ('cat4ptr', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grdsrl', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('grdpa', models.FloatField()),
                ('grade', models.CharField(default='N', max_length=1)),
                ('semnum', models.IntegerField()),
                ('cat1ptrern', models.IntegerField(default=0)),
                ('cat2ptrern', models.IntegerField(default=0)),
                ('cat3ptrern', models.IntegerField(default=0)),
                ('cat4ptrern', models.IntegerField(default=0)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Student')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Courses')),
            ],
        ),
    ]
