# Generated by Django 2.1.4 on 2019-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_courses_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grdsrl',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
