# Generated by Django 2.1.4 on 2019-02-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20190219_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='cat1ptr',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='cat2ptr',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='cat3ptr',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='cat4ptr',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='cat1ptrern',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='cat2ptrern',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='cat3ptrern',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='cat4ptrern',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cat1ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cat2ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cat3ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cat4ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='credits',
        ),
    ]
