# Generated by Django 2.1.4 on 2019-02-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20190219_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_credits',
            field=models.FloatField(default=0.0),
        ),
    ]
