# Generated by Django 2.1.4 on 2019-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_student_total_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
