# Generated by Django 2.1.4 on 2019-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_courses_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='corecgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='sepscgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='unicgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
