# Generated by Django 2.1.4 on 2019-04-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_auto_20190226_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semunmber',
            field=models.IntegerField(default=0),
        ),
    ]
