# Generated by Django 2.1.4 on 2019-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_student_semunmber'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='hardware',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='literature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='math',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='software',
            field=models.IntegerField(default=0),
        ),
    ]
