# Generated by Django 2.1.4 on 2019-04-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_auto_20190413_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='coursetitle',
            field=models.CharField(default=2121, max_length=100),
            preserve_default=False,
        ),
    ]
