# Generated by Django 2.1.4 on 2019-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_courses_coursetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainBox',
            fields=[
                ('Complain_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Complaining_person', models.CharField(max_length=30)),
                ('Complainer_email', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LostandFound',
            fields=[
                ('lost_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('loser_id', models.IntegerField()),
                ('loser_contact_email', models.CharField(max_length=40)),
                ('lost_item', models.CharField(max_length=400)),
            ],
        ),
    ]
