# Generated by Django 2.1.4 on 2019-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_complainbox_lostandfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='finders_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostandfound',
            name='loser_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
