# Generated by Django 2.1.4 on 2019-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_auto_20191212_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='itemtype',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
