# Generated by Django 2.1.4 on 2019-12-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_auto_20191212_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostandfound',
            old_name='loser_contact_email',
            new_name='finder_contact_email',
        ),
    ]
