# Generated by Django 2.1.4 on 2019-12-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_auto_20191220_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationscripts',
            old_name='comment',
            new_name='commentinput',
        ),
    ]
