# Generated by Django 2.1.4 on 2019-12-22 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAssistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainBox',
            fields=[
                ('Complain_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Complaining_person', models.CharField(max_length=30)),
                ('Complainer_email', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='id',
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='courseid',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='coursename',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='coursetitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='credits',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='hardware',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='literature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='math',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='software',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grades',
            name='Course_name',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grades',
            name='Student_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grades',
            name='grade',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='grades',
            name='grdpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='grades',
            name='grdsrl',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grades',
            name='semnum',
            field=models.IntegerField(default=0),
        ),
    ]
