# Generated by Django 2.1.4 on 2019-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_auto_20191220_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationscripts',
            name='eval_id',
        ),
        migrations.AddField(
            model_name='evaluationscripts',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
