# Generated by Django 2.1.4 on 2019-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainBox',
            fields=[
                ('Complain_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Complaining_person', models.CharField(max_length=30)),
                ('Complainer_email', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('coursename', models.CharField(max_length=5)),
                ('coursetitle', models.CharField(max_length=100)),
                ('credits', models.FloatField()),
                ('priority', models.IntegerField()),
                ('category', models.CharField(max_length=6)),
                ('software', models.IntegerField(default=0)),
                ('hardware', models.IntegerField(default=0)),
                ('math', models.IntegerField(default=0)),
                ('literature', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScripts',
            fields=[
                ('eval_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('faculty_name', models.CharField(max_length=200)),
                ('option1_input', models.CharField(max_length=100)),
                ('option2_input', models.CharField(max_length=100)),
                ('option3_input', models.CharField(max_length=100)),
                ('option4_input', models.CharField(max_length=100)),
                ('option5_input', models.CharField(max_length=100)),
                ('option6_input', models.CharField(max_length=100)),
                ('commentinput', models.CharField(max_length=1000)),
                ('submitter_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grdsrl', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('grdpa', models.FloatField(default=0.0)),
                ('grade', models.CharField(default='N', max_length=1)),
                ('semnum', models.IntegerField(default=0)),
                ('Student_id', models.IntegerField()),
                ('Course_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LostandFound',
            fields=[
                ('lost_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('finders_id', models.IntegerField()),
                ('itemtype', models.CharField(max_length=30)),
                ('loser_id', models.IntegerField(default=None, null=True)),
                ('finder_contact_email', models.CharField(max_length=40)),
                ('lost_item', models.CharField(max_length=400)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uni_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('cgpa', models.FloatField(default=0.0)),
                ('total_credits', models.FloatField(default=0.0)),
                ('sepscgpa', models.FloatField(default=0.0)),
                ('corecgpa', models.FloatField(default=0.0)),
                ('unicgpa', models.FloatField(default=0.0)),
                ('semunmber', models.IntegerField(default=0)),
            ],
        ),
    ]
